param(
  [Parameter(Mandatory = $true)]
  [string]$ProjectName,

  [string]$DestinationRoot = "D:\workspace\8thwall example\8thwall_ar",
  [string]$TemplatePath = "D:\workspace\8thwall example\8thwall_ar\8thwall-engine-image-target-template",
  [string]$GlbPath = "",
  [string]$ImageTargetDir = ""
)

$ErrorActionPreference = "Stop"

if ($ProjectName -notmatch "^[a-zA-Z0-9][a-zA-Z0-9._-]*$") {
  throw "ProjectName must contain only letters, numbers, dots, underscores, or hyphens, and cannot start with punctuation."
}

$template = Resolve-Path -LiteralPath $TemplatePath
$root = Resolve-Path -LiteralPath $DestinationRoot
$destination = Join-Path $root.Path $ProjectName

if (Test-Path -LiteralPath $destination) {
  throw "Destination already exists: $destination"
}

New-Item -ItemType Directory -Path $destination | Out-Null

foreach ($item in @("src", "config", "external", "image-targets", ".github")) {
  $sourceItem = Join-Path $template.Path $item
  if (Test-Path -LiteralPath $sourceItem) {
    Copy-Item -LiteralPath $sourceItem -Destination $destination -Recurse
  }
}

foreach ($file in @(".gitattributes", ".gitignore", "LICENSE", "package.json", "package-lock.json", "TEMPLATE.md", "tsconfig.json")) {
  $sourceFile = Join-Path $template.Path $file
  if (Test-Path -LiteralPath $sourceFile) {
    Copy-Item -LiteralPath $sourceFile -Destination $destination
  }
}

$packageJsonPath = Join-Path $destination "package.json"

$packageJson = Get-Content -Raw -LiteralPath $packageJsonPath | ConvertFrom-Json
$packageJson.name = $ProjectName
$packageJson | ConvertTo-Json -Depth 20 | Set-Content -LiteralPath $packageJsonPath -Encoding UTF8

if ($GlbPath) {
  $glb = Resolve-Path -LiteralPath $GlbPath
  Copy-Item -LiteralPath $glb.Path -Destination (Join-Path $destination "src\assets\christmas.glb") -Force
}

if ($ImageTargetDir) {
  $targetDir = Resolve-Path -LiteralPath $ImageTargetDir
  if (-not (Test-Path -LiteralPath (Join-Path $targetDir.Path "target.json"))) {
    throw "ImageTargetDir must contain target.json generated by 8th Wall."
  }
  $projectTargetDir = Join-Path $destination "image-targets"
  if (Test-Path -LiteralPath $projectTargetDir) {
    Remove-Item -LiteralPath $projectTargetDir -Recurse -Force
  }
  Copy-Item -LiteralPath $targetDir.Path -Destination $projectTargetDir -Recurse
}

Write-Output "Created 8th Wall Engine image target project: $destination"
